apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: hp.test
      http:
        paths:
          - path: /app(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-srv
                port:
                  number: 4002
          # - path: /bg/?(.*)
          #   backend:
          #     serviceName: bg-srv
          #     servicePort: 4000
          # - path: /?(.*)
          #   backend:
          #     serviceName: rabbitmq-srv
          #     servicePort: 15672